on: 
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - created

name: luci-app-xclient
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      URL: https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
      REPF: ${{ github.repository }}
      PKGN: ${{ 'luci-app-xclient' }}

    steps:
    - name: Checkout - ${{ github.ref }}
      uses: actions/checkout@master

    - name: Prepare SDK ENV
      run: |
        wget -q "${URL}"
        tar xJf openwrt-sdk-*.tar.xz -C ../
        mv -f "${GITHUB_WORKSPACE}" ../src
        mv ../openwrt-sdk-* "${GITHUB_WORKSPACE}"

    - name: Install dependencies
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: TAG
      run: |
          tag_name="${GITHUB_REF##*/}"
          echo Tag $tag_name
          echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV
          
    - name: Prepare targets
      run: |
        REP=$(basename "${REPF}")
        mv -vf ../src "package/${REP}"


    - name: Load custom configuration
      env:
        DEBIAN_FRONTEND: noninteractive
        CONFIG_FILE: '.config'
      run: |
        REP=$(basename "${REPF}")
        [ -e "package/${REP}/${CONFIG_FILE}" ] && mv "${CONFIG}" .config
        make defconfig

    - name: Build target
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        make package/${PKGN}/compile -j$(nproc) V=s
        mkdir ../bin
        find bin/ -type f -name "*${PKGN}*" | xargs -t -i mv -vf {} ../bin

    - name: Upload - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: ${{ format('{0}.{1}.{2}', github.workflow, github.actor, github.event_name) }}
        path: ../bin
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          draft: true
          name: ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          files: ../bin/*.ipk
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
